### ISSUE TITLE
Toggling flash per capture

### ISSUE THREAD

**Issue by mevinDhun** [QuinnFreedman/Camera3#2]
Hi, 
i am trying to use the sample code provided and i want to toggle the flash on/off after having created the preview. I tried overriding it like this but it has no effect on the flash. Is that the right way to do it?
```java
public void takePicture() {
        CaptureRequestConfiguration config = new CaptureRequestConfiguration() {
            @Override
            public void configure(CaptureRequest.Builder request) {
                request.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_ON_ALWAYS_FLASH);
            }
        };

        cameraManager.captureImage(captureSession,config, config);
    }
```

**Comment by QuinnFreedman** [comment]
Your code looks pretty reasonable to me, but I got the same issue when I copied it. What I did instead which *did* work was:

```java
    public void takePicture() {
        CaptureRequestConfiguration config = new CaptureRequestConfiguration() {
            @Override
            public void configure(CaptureRequest.Builder request) {
                request.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_ON);
                request.set(CaptureRequest.FLASH_MODE, CaptureRequest.FLASH_MODE_SINGLE);
            }
        };

        cameraManager.captureImage(captureSession, Camera3.PRECAPTURE_CONFIG_NONE, config);
    }
```
*Confirmed works on `0.4.0` which I will upload in a minute.*

You can read the docs for [`CaptureRequest.FLASH_MODE`](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.html#FLASH_MODE) if you want to try to figure out why but it honestly makes no sense. Just one of the reasons this API is such a mess.

You might also want to check [`CameraCharacteristics.FLASH_INFO_AVAILABLE`](https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics#FLASH_INFO_AVAILABLE). There is a pretty wild variation in behavior between different hardware. That's something I'll try to address sooner or later but its part of the nature of being built on top of Camera2.

---

**Another note:** the two configs in `captureImage` are for *precapture* and *capture*. The way Camera2 works is it's basically a constant stream of requests going back and forth to the camera and not every "request" actually means an image is being captured. You can use them for things like requesting that the camera start its auto-focus sequence and then many requests later it might tell you that it's done.

So for Camera3 I let you specify one precapture request to start focus/exposure stuff like that, but you probably (maybe) don't want to use a `FLASH_MODE_SINGLE` request for both requests because it just will look like two flashes back-to-back. If you want to do some red-eye reducing preflash, you might want to look at [`CONTROL_AE_MODE_ON_AUTO_FLASH_REDEYE`](https://developer.android.com/reference/android/hardware/camera2/CameraMetadata#CONTROL_AE_MODE_ON_AUTO_FLASH_REDEYE) but I honestly haven't used that before. Red-eye-reduction is a pretty basic thing though so I should probably figure out the best way to do that and put in a prefab config for it.

**Comment by mevinDhun** [comment]
Thanks for the quick reply. I have tried your fix and it works. I noticed an issue, when i rotate my application, the preview gets distorted. Is there a callback that i can use to recompute the preview size without stopping the camer?

**Comment by QuinnFreedman** [comment]
Sorry for the delay this time. Is your issue that the preview pauses when the app rotates? That is a side effect of the solution I suggested. If you don't want that to happen, you might be able to handle the rotation yourself.

As far as I know, if you're using the AutoFitTextureView, then all the work of stretching/cropping the image is being set up in [`AutoFitTextureView.setAspectRatio()`](https://quinnfreedman.github.io/Camera3/com/avalancheevantage/android/camera3/AutoFitTextureView.html#setAspectRatio-int-int-). It's possible that when you rotate the device you could manually set the aspect ratio to the rotated version and just keep the preview working. I haven't tested that idea though.

You could also try to prevent that texture view from rotating relative to the screen when the rest of the app does. I'm not actually sure if there is a way to do this but if you could somehow keep it with the same width and height, just rotated relative to the rest of the scene, that would work. Maybe there is an Android View equivalent of CSS's `transform:rotate`? I'm really not sure though.

You might also be interested in [`Camera3.setCaptureCallback()`](https://quinnfreedman.github.io/Camera3/com/avalancheevantage/android/camera3/Camera3.html#setCaptureResultListener-com.avalancheevantage.android.camera3.CaptureResultListener-). This lets you listen to the response form every request that gets sent to the camera (including the repeating preview request). You could check [`CaptureResult.JPEG_ORIENTATION`](https://developer.android.com/reference/android/hardware/camera2/CaptureResult#JPEG_ORIENTATION) to see what orientation the image itself is in. That might help inform how to display it.

I'll try out some of those solutions when I get a chance and if they don't work maybe I can add something to handle this.

**Comment by mevinDhun** [comment]
i fixed it by monitoring the orientation chnages and recalling setAspectRatio:
```java
WindowManager mWindowManager = (WindowManager) getActivity().getSystemService(Context.WINDOW_SERVICE);
        OrientationEventListener orientationEventListener = new OrientationEventListener(getActivity(), SensorManager.SENSOR_DELAY_NORMAL) {
            @Override
            public void onOrientationChanged(int orientation) {
                Display display = mWindowManager.getDefaultDisplay();
                int rotation = display.getRotation();
                if (rotation != mLastRotation) {
                    //rotation changed
                    if (cameraSize == null)
                        return;
                    if (rotation == Surface.ROTATION_90 || rotation == Surface.ROTATION_270) {
                        //landscape
                        previewTexture.setAspectRatio(cameraSize.getWidth(), cameraSize.getHeight());
                    } else {
                       //portrait
                        previewTexture.setAspectRatio(cameraSize.getHeight(), cameraSize.getWidth());
                    }
                }
                mLastRotation = rotation;
            }
        };

        if (orientationEventListener.canDetectOrientation())
            orientationEventListener.enable();
```

**Comment by mevinDhun** [comment]
Regarding your sample code for flash, it works but always gets the image overexposed. Do you have how to have the camera regulate the flash level?

**Comment by QuinnFreedman** [comment]
@mevinDhun, I got a couple issues a little messed up. It looks like you found a solution to your rotation problem, but I wrote about a similar issue in #3.

For the over-exposing problem, I created a new issue which I am working on: #4.
