### ISSUE TITLE
Question: Need to pass in the stillCaptureHandler twice?

### ISSUE THREAD

**Issue by salamanders** [QuinnFreedman/Camera3#8]
When configuring, I pass in the **stillCaptureHandler**:

`cameraManager.startCaptureSession(cameraId, null, Collections.singletonList(stillCaptureHandler))`

And when taking a picture, I pass in the handler:

`cameraManager.captureImage(
        stillCaptureHandler,
        Camera3.PRECAPTURE_CONFIG_TRIGGER_AUTO_EXPOSE,
        Camera3.CAPTURE_CONFIG_DEFAULT
)`

... is this a correct understanding?  the docs for StillCaptureHandler say "It should be created once and passed to Camera3.startCaptureSession(String, PreviewHandler, List) when the capture session is started. " - but then it seems like I need it again when I actually trigger the capture.

Thanks!

**Comment by QuinnFreedman** [comment]
Yes, that is correct. I'm aware it's a pretty dumb design but it has to be that way because of the way Android's built-in API works, if I understand it correctly -- you need to register any surfaces you might want to capture to before you actually start.

I emphasized creating it once just as opposed to creating a new, anonymous handler for every image you capture, which might be a common pattern but would not work for the reason above.

**Comment by salamanders** [comment]
That makes sense, thank you!
